version: '3'

volumes:
  gitea-data:
  db:
  drone-db:

networks:
  gitea-net:
    external: false
  proxy:
    external: true

services:
  gitea-server:
    image: gitea/gitea:latest
    ports:
      - '8380:3000'
      - '10022:22'
    networks:
      - proxy
      - gitea-net
    volumes:
      - '/home/matt/docker-swarm/gitea:/data'
      - '/home/matt/docker-swarm/gitea/data:/data/gitea'
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain.1=gitea.basement.lan
        - com.df.port.1=8380
        - com.df.serviceDomain.2=gitea.basement.lan
        - com.df.port.2=10022
        - com.df.srcPort.2=10022

  gitea-db:
    image: postgres:alpine
    networks:
      - gitea-net
    ports:
      - '5440:5432'
    volumes:
      - /home/matt/docker-swarm/data/gitea/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=gitea
    deploy:
      mode: replicated
      replicas: 1

  drone-server:
    image: drone/drone:0.8
    ports:
      - '8381:8000'
      - '9000:9000'
    volumes:
      - drone-db:/var/lib/drone/
    environment:
      - DRONE_OPEN=true
      - DRONE_HOST=http://drone.basement.lan:8381
      - DRONE_SECRET=test
      - DRONE_GITEA=true
      - DRONE_GITEA_URL=http://gitea.basement.lan:8381/
      - DRONE_NETWORK=gitea-net
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain.1=drone.basement.lan
        - com.df.port.1=8381
        - com.df.srcPort.1=8381
        - com.df.serviceDomain.2=drone.basement.lan
        - com.df.port.2=9000
        - com.df.srcPort.2=9000

  drone-agent:
    image: drone/agent:0.8
    command: agent
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=drone.basement.lan:9000
      - DRONE_SECRET=test
    deploy:
      mode: replicated
      replicas: 1
