version: '3'

services:

  gitlab-ci-runner:
    networks:
      - gitlab-net
    image: 'sameersbn/gitlab-ci-multi-runner:1.1.4-4'
    volumes:
      - '/home/matt/docker-swarm/data/gitlab/gitlab-ci-runner:/home/gitlab_ci_multi_runner/data'
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      - CI_SERVER_URL=http://gitlab.basement.lan
      - RUNNER_TOKEN=fKd5LLQjHX7MogDumV7z
      - RUNNER_DESCRIPTION=GitLab CI Multi Runner
      - RUNNER_EXECUTOR=docker
      - DOCKER_IMAGE=docker:1.11.2
    deploy:
      mode: replicated
      replicas: 1
    logging:
      driver: gelf
      options:
        gelf-address: 'udp://127.0.0.1:12201'
        tag: gitlab_runner

networks:
  gitlab-net:
    external: false
